#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '\n ==========================================================================\n\n  🏗️👷 Pre-commit checks: Styling, testing and building your project.\n\n ==========================================================================\n'


echo '\n =====================================\n ✍️👩‍🔬 Formatting checks...\n =====================================\n'
nx affected -t format:check ||
(
    echo '🤢🤮🤢🤮 Your formatting fails. 🤢🤮🤢🤮
           Run `nx affected -t format:write` to format your code and try commit again.';
    false;
)


echo '\n =====================================\n👩‍🔬👀 ESLint checks...\n =====================================\n'
nx affected -t lint ||
(
    echo '🤢🤮🤢🤮 Your ESLint code styling fails. 🤢🤮🤢🤮
           Run `nx affected -t lint` to check your code style, apply fixes and try commit again.';
    false;
)

echo '\n =====================================\n🛠️⚙️ TypeScript types check...\n =====================================\n'
nx affected -t typecheck ||
(
    echo '🤡😂❌🤡 Failed TS Type check. 🤡😂❌🤡
            Are you seriously trying to write that? Run `nx affected -t typecheck `, make the changes required and try commit again.'
    false;
)


echo '\n =====================================\n 🏃‍♀️🏃‍♂️🏃🏽 Running unit tests...\n =====================================\n'
nx affected -t test ||
(
    echo '🤡😂❌💥 Kaboom!!! Failed Unit tests. 💥🤡❌🤡
            Seriously 😜? Run `nx affected -t test`. Apply fixes and try commit again.'
    false;
)


echo '\n =====================================\n 🐌🐌🐌 Running End-to-end tests...\n =====================================\n'
nx affected --parallel 1 -t e2e-ci  ||
(
    echo '🤡😂😜😜 Ha! Failed E2E tests. 🤡😂😜😜
            Well 😜, check your ui changes - maybe not your fault. Run again `nx affected -t e2e --ui` with UI option. Apply fixes if needed and try commit again.'
    false;
)


echo '\n =====================================\n 🏗️👷🛠️ Making production build...\n =====================================\n'
nx run fe:build ||
(
    echo '❌👷🔨❌ Better call Bob Marley... Because the app build has failed ❌👷🔨❌
            Try to re-build `nx run fe:build`, then check for errors to see why. 
    '
    false;
)

echo '\n ===================================================================================\n\n✅✅✅✅ You are Great! 👍 All checks passed... I am committing this now. ✅✅✅✅ \n\n ===================================================================================\n'