name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - run: npm ci
      - uses: nrwl/nx-set-shas@v4

      - name: Linting, testing and building
        run: npx nx affected -t lint test build

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: E2E test running
        run: npx nx affected --parallel 1 -t e2e-ci
        continue-on-error: true
